### ISSUE TITLE
Error when executing yarn build

### ISSUE THREAD

**Issue by omidp** [axelor/axelor-mobile#231]
Hi, 

I followed step by step installation guide,however, when I execute `yarn build`, I am getting multiple errors. 

```
src/components/templates/ObjectCard/ObjectCard.tsx(245,14): error TS2746: This JSX tag's 'children' prop expects a single child of type 'ReactNode', but multiple children were provided.
 src/components/templates/ObjectCard/ObjectCard.tsx(291,13): error TS2769: No overload matches this call.
         Overload 1 of 2, '(props: ViewProps | Readonly<ViewProps>): View', gave the following error.
           Type 'Element[]' is not assignable to type 'ReactNode'.
         Overload 2 of 2, '(props: ViewProps, context: any): View', gave the following error.
           Type 'Element[]' is not assignable to type 'ReactNode'.
       npm ERR! Lifecycle script `compile` failed with error: 
       npm ERR! Error: command failed 
       npm ERR!   in workspace: @axelor/aos-mobile-ui@7.1.0 
```

I am using Linux(Ubuntu), node version v16.20.2, java 11.0.19, yarn 1.22.19, axelor-mobile 7.1.1/master.

```
>  NX   Ran target build for 7 projects (3s)
 
    ✔    1/2 succeeded [0 read from cache]
 
    ✖    1/2 targets failed, including the following:
         - nx run @axelor/aos-mobile-ui:build
```

Any help and advice is appreciated.

**Comment by lme-axelor** [comment]
Hello,

Thank you for the detailled error report.

Current master branch is broken due to dependencies updates. Those errors are type errors. You can go to dev branch which contains the next patch version to work on the application. 
The next patch version, which will be released soon, fixes all the errors.

**Comment by lme-axelor** [comment]
Hello,

Version 7.1.2 and version 7.2.0 have been released now, your error should be fixed.
I'm closing this, do not hesitate to post again if you have any issue.
