### ISSUE TITLE
Error when running yarn android command: Cannot read property 'useRef' of null

### ISSUE THREAD

**Issue by lhing17** [axelor/axelor-mobile#52]
### Overview of the Issue
I followed the installation guide step by step and did not encounter any errors during the install process. However, when I tried to run the yarn android command, I got the following error: 
```text
 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Application (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aosmobile&modulesOnly=false&runModule=true:204825:31)
    at App
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aosmobile&modulesOnly=false&runModule=true:65710:36)
    at AosMobile(RootComponent) (http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.aosmobile&modulesOnly=false&runModule=true:71133:28)

TypeError: Cannot read property 'useRef' of null

This error is located at:
    in Application (at App.js:29)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in AosMobile(RootComponent) (at renderApplication.js:60), js engine: hermes
```

### What I try
I expected the command to launch the app on my device, but instead it failed with the error message.

I searched the documentation and the existing issues, but I could not find a solution for this problem. I tried to change the version of React and react native. When I changed react to v17.0.2, the error still occured. When I changed react native to v0.69.8, the app just crashed.

### Environment
I am using Windows 10, Node.js v18.15.0, and yarn v1.22.19. I am using a git bash instead of CMD.

Can anyone help me with this issue? Thank you.

**Comment by lhing17** [comment]
I tried using MacOS and the issue didn’t occur. Could you please let me know if this project uses any libraries related to the operating system?

**Comment by lme-axelor** [comment]
Hello,
we don't use any library depending on the operating system, maybe the error came from the version management. 
The project depends on react 18.2.0, react-native 0.68.1 and Node.js 16.x.
